--DIMP duplicados (Principalmente Amazon)
DELETE  D_WRKDB.WRK_HIST_SIT_OPER_MEIO_PAGTO_ATULZ_DUP;
INSERT INTO D_WRKDB.WRK_HIST_SIT_OPER_MEIO_PAGTO_ATULZ_DUP(CD_DECL_FISC, CD_SIST_ORIG, CD_SEQ_UNICO_ADQUI, CD_AUT, CD_TRANS, CD_MEIO_CAPT_MEIO_PAGTO, IN_TRANS_PAGTO_EXT, DT_OPER, CD_CLIENTE_MEIO_PAGTO, IN_INF_EXT, DT_INI_INF_CLIENTE, DT_FIM_INF_CLIENTE, NU_CNPJ_ADQUI, CD_INSTIT_PARC_MEIO_PAGTO, VL_OPER, DT_INI_VIG, DT_FIM_VIG, CD_SIT_OPER_MEIO_PAGTO, CD_TIPO_CANCEL_MEIO_PAGTO, CD_SIT_DECL_FISC, CD_IND_ATULZ, NU_EXECUCAO_PROCESSO)
    SELECT P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.CD_DECL_FISC_STG,
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.CD_SIST_ORIG,
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.NU_SEQ_ADQUI_STG,
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.CD_AUT_STG,
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.CD_TRANS_STG,
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.CD_MEIO_CAPT,
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.IN_TRANS_PAGTO_EXT,
        CAST(CAST(P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.DT_OPER AS TIMESTAMP(6)) AS DATE),
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.CD_CLIENTE,
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.IN_INF_EXT,
        CAST(CAST(P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.DT_INI_INF_CNPJ AS TIMESTAMP(6)) AS DATE),
        CAST(CAST(P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.DT_FIM_INF_CNPJ AS TIMESTAMP(6)) AS DATE),
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.NU_CNPJ_ADQUI_STG,
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.CD_INSTIT_PARC_MEIO_PAGTO_STG,
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.VL_OPER,
        CAST(CAST(P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.DT_INI_VIG AS TIMESTAMP(6)) AS DATE),
        CAST(CAST(P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.DT_FIM_VIG AS TIMESTAMP(6)) AS DATE),
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.CD_SIT_OPER,
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.CD_TIPO_CANCEL,
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.CD_SIT_DECL_FISC,
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.CD_IND_ATULZ,
        P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO.NU_EXECUCAO_PROCESSO
        FROM P_WRKDB.VW_HIST_SIT_OPER_MEIO_PAGTO
;


SELECT * FROM D_WRKDB.WRK_HIST_SIT_OPER_MEIO_PAGTO_ATULZ_DUP
QUALIFY SUM(1) OVER (PARTITION BY 
CD_DECL_FISC ,
CD_SEQ_UNICO_ADQUI ,CD_AUT ,CD_TRANS ,CD_MEIO_CAPT_MEIO_PAGTO ,
IN_TRANS_PAGTO_EXT ,DT_OPER ,CD_CLIENTE_MEIO_PAGTO ,IN_INF_EXT ,
DT_INI_INF_CLIENTE ,DT_FIM_INF_CLIENTE ,NU_CNPJ_ADQUI ,VL_OPER 
) > 1;


--Pegar CD_DECL_FISC na query anterior
LOCK ROW FOR ACCESS
SEL *
FROM P_TGTDB.ERL_DECL_FISC
WHERE CD_DECL_FISC = 130007852001202301;

/* --VERIFICAR VERSÃO DO ARQUIVO (Pegar nome do arquivo na query anterior)
SEL DISTINCT CD_VERSAO
FROM P_ARQDB.ARQ_DIMP
WHERE NM_ARQ = 'W0007852-001.txt'
*/

--procedimento
UPDATE P_CTLDB.CTL_CARAC_CARGA_ARQDB SET VL_INF = 'ARQUIVO REJEITADO MANUALMENTE POR CONTER REGISTROS DUPLICADOS' WHERE NM_ARQ = 'W0007852-001.txt' AND DS_INF = 'DS_STATUS';
UPDATE P_CTLDB.CTL_CARAC_CARGA_ARQDB SET VL_INF = 'REJ' WHERE NM_ARQ = 'W0007852-001.txt' AND DS_INF = 'CD_STATUS';


--Retomar o WRF_CARGA_DIMP