--STG

DROP TABLE P_STGDB.STG_RPR_USUAR
;

CREATE MULTISET TABLE P_STGDB.STG_RPR_USUAR
(
     cpf_usuario BIGINT,
     cd_grupo   VARCHAR(10),
     nm_grupo   VARCHAR(100),
     status	VARCHAR(10)
)PRIMARY INDEX(cpf_usuario)
;

DROP TABLE P_STGDB.STG_RPR_USUAR_STATUS
;

CREATE MULTISET TABLE P_STGDB.STG_RPR_USUAR_STATUS
(
     cpf_usuario BIGINT,
     status VARCHAR(10)
)PRIMARY INDEX(cpf_usuario)
;

--WRK

CREATE MULTISET TABLE P_WRKDB.WRK_TR_GRUPO_USUAR_RPR, FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     	(
      	CD_GRUPO_RPR SMALLINT NOT NULL,
      	NM_GRUPO_RPR VARCHAR(200) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	NU_EXECUCAO_PROCESSO INTEGER NOT NULL
	)
PRIMARY INDEX ( CD_GRUPO_RPR );

CREATE MULTISET TABLE P_WRKDB.WRK_STATUS_USUAR_RPR, FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
	(
	NU_CPF_USUAR_RPR BIGINT NOT NULL,
	CD_GRUPO_RPR SMALLINT NOT NULL,
   	DS_STATUS_USUAR_RPR VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	NU_EXECUCAO_PROCESSO INTEGER NOT NULL
	)
PRIMARY INDEX ( NU_CPF_USUAR_RPR );

--TGT

CREATE MULTISET TABLE P_TGTDB.ERL_TR_GRUPO_USUAR_RPR, FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     	(
      	CD_GRUPO_RPR SMALLINT NOT NULL,
      	NM_GRUPO_RPR VARCHAR(200) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	NU_EXECUCAO_PROCESSO INTEGER NOT NULL
	)
PRIMARY INDEX ( CD_GRUPO_RPR );

COLLECT STATISTICS 
	-- default SYSTEM SAMPLE PERCENT 
        -- default SYSTEM THRESHOLD PERCENT 
        COLUMN ( CD_GRUPO_RPR  ) , 
        COLUMN ( NM_GRUPO_RPR )  
ON P_TGTDB.ERL_TR_GRUPO_USUAR_RPR ;

CREATE MULTISET TABLE P_TGTDB.ERL_STATUS_USUAR_RPR, FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
	(
	NU_CPF_USUAR_RPR BIGINT NOT NULL,
	CD_GRUPO_RPR SMALLINT NOT NULL,
   	DS_STATUS_USUAR_RPR VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
	NU_EXECUCAO_PROCESSO INTEGER NOT NULL
	)
PRIMARY INDEX ( NU_CPF_USUAR_RPR );

COLLECT STATISTICS 
	-- default SYSTEM SAMPLE PERCENT 
        -- default SYSTEM THRESHOLD PERCENT 
        COLUMN ( NU_CPF_USUAR_RPR  ) , 
        COLUMN ( CD_GRUPO_RPR )  ,
        COLUMN ( DS_STATUS_USUAR_RPR )              
ON P_TGTDB.ERL_STATUS_USUAR_RPR ;
                


INSERT INTO P_CTLDB.CTL_PROCESSO (CD_PROCESSO, NU_FILA, DS_PROCESSO, ID_LOCAL_FILA)
VALUES ('RPR0000W', 64, 'WRK_TR_GRUPO_USUAR_RPR', '0');

INSERT INTO P_CTLDB.CTL_PROCESSO (CD_PROCESSO, NU_FILA, DS_PROCESSO, ID_LOCAL_FILA)
VALUES ('RPR0000T', 64, 'ERL_TR_GRUPO_USUAR_RPR', '0');

INSERT INTO P_CTLDB.CTL_PROCESSO (CD_PROCESSO, NU_FILA, DS_PROCESSO, ID_LOCAL_FILA)
VALUES ('RPR0001W', 64, 'WRK_STATUS_USUAR_RPR', '0');

INSERT INTO P_CTLDB.CTL_PROCESSO (CD_PROCESSO, NU_FILA, DS_PROCESSO, ID_LOCAL_FILA)
VALUES ('RPR0001T', 64, 'ERL_STATUS_USUAR_RPR', '0');


